apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: yamlconfigmap
          mountPath: /usr/share/nginx/html

      volumes:
      - name: yamlconfigmap
        configMap:
            name: nginx-configmap
            items:
            - key: indexhtml
              path: index.html
