AwsTemplateFormatVesrion: 2010-09-09

Descripion: Basic Network

Parameters: 
  VpcCidr:
    Description: VpcCidr
    Type: String
    Default: 10.20.0.0/16
  Environment:
    Description: environment
    Type: String
    Default: lab

  Project:
    Description: project
    Type: String
    Default: FRI

Resources: 
  Vpc: 
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: !Ref VpcCidr
    EnableDnsSupport: true
    EnableDnsHostnames: true
    Tags:
     - Key: stack
       Value: production

myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:

