apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_PASSWORD: "cGFzc3dvcmQ=" #username
  MONGO_USERNAME: "dXNlcm5hbWU=" #password
