apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
  #- protocol: TCP mozno toto doplnit idk
  