apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  tasks:
  - name: git-clone-task
    taskRef:
      name: git-clone
    workspaces:
    - name: shared-workspace
    params:
    - name: url
      value: https://github.com/cisko6/onpk_K8s-docker-helm-tekton-openstack.git
    - name: revision
      value: main  # or specify a branch/tag

  - name: buildah-task
    taskRef:
      name: buildah
    workspaces:
    - name: shared-workspace
    params:
    - name: buildahArguments
      value: "bud -t cisko6/tekton-backend:latest -f ./Docker/zauni-zadanie-appbackend/Dockerfile ."
    - name: pushImage
      value: "cisko6/tekton-backend:latest"

  - name: push-to-registry-task
    taskRef:
      name: buildah
    workspaces:
    - name: shared-workspace
    params:
    - name: buildahArguments
      value: "push cisko6/tekton-backend:latest"

  workspaces:
  - name: shared-workspace
    description: "Shared workspace for tasks"
