apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-build-and-push-pipeline
  namespace: helm
spec:
  tasks:
  - name: git-clone-task
    taskRef:
      name: git-clone
    workspaces:
    - name: shared-workspace
    params:
    - name: url
      value: https://github.com/cisko6/onpk_K8s-docker-helm-tekton-openstack.git
    - name: revision
      value: main  # or specify a branch/tag

  - name: buildah-task
    taskRef:
      name: buildah
    workspaces:
    - name: shared-workspace
    params:
    - name: IMAGE  # Add a parameter for IMAGE
      value: "cisko6/tekton-frontend:latest"  # Provide a default value for IMAGE
    - name: buildahArguments
      value: "bud -t cisko6/tekton-frontend:latest -f ./Docker/zauni-zadanie-appfrontend/Dockerfile ."
      #value: "bud -t $(params.IMAGE) -f ./Docker/zauni-zadanie-appfrontend/Dockerfile ."
    - name: pushImage
      value: "cisko6/tekton-frontend:latest"

  - name: push-to-registry-task
    taskRef:
      name: buildah
    workspaces:
    - name: shared-workspace
    params:
    - name: buildahArguments
      value: "push cisko6/tekton-frontend:latest"

  workspaces:
  - name: shared-workspace
    description: "Shared workspace for tasks"
