apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver-deployment
  name: webserver-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver
  type: ClusterIP
  