
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-clone-build-push
  namespace: helm
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with buildah and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
    - name: dockerfile
      type: string
    - name: context
      type: string
  workspaces:
    - name: shared-data
    - name: docker-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: shared-data

    - name: build-push
      runAfter: ["fetch-source"]
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.context)
        - name: SKIP_PUSH
          value: false
        - name: FORMAT
          value: docker
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials

    - name: update-image-version
      runAfter: ["build-push"]
      taskSpec:
        steps:
          - name: update-version
            image: alpine:3.18
            script: |
              #!/usr/bin/env sh
              apk add --no-cache yq
              yq -i 'image = "$(params.IMAGE)"' $(workspaces.source.path)/Helm/values-fe.yaml
          - name: check
            image: alpine:3.18
            command: ["cat"]
            args:
              - "$(workspaces.source.path)/Helm/values-fe.yaml"
        params:
          - name: IMAGE
      params:
        - name: IMAGE
          value: $(params.image-reference)
      workspaces:
        - name: source
          workspace: shared-data

    # - name: deploy-app
    #   runAfter: ["update-image-version"]
    #   taskSpec:
    #     steps:
    #       - name: deploy-to-k8s
    #         image: bitnami/kubectl:latest
    #         args:
    #           - "apply"
    #           - "-f"
    #           - "$(workspaces.source.path)/k8s/python-demo-app/"
    #   workspaces:
    #     - name: source
    #       workspace: shared-data
